### PR TITLE
get_vault, get_group, get_user, list_event Implementation

### PR DESCRIPTION
**Pull request by acabey-klaviyo**
This is a pretty naive implementation which just returns the decoded JSON dict from the response. I am absolutely open to taking another approach to it by creating native python objects to represent vault, group, user; I just went at it the most straightforward way I could think of.

I've tried to follow your conventions for error handling, but again I am open to critique.

I forked this in order to add in these features for some automation tasks, but given that your upstream is still under pretty active development, I figured it would be more sustainable to make the PR and coordinate with you on a proper implementation.

### CODE REVIEW

**Comment by zcutlip** [comment]
Thanks for the PR! It looks really good. You did a fine job following my conventions even though they're a bit weird.

A few thoughts:
- I think just returning the decoded dictionary should be fine in these instances.
  - The reason I did python objects with "get item" is that there isn't any one "item" but a bunch of different item templates 
- I've got some substantial changes to the internals coming to help support automated testing. I don't think any of it should impact the API you've added, but let me think on it for a bit
- Regarding event listing: I can't test/verify this unfortunately since it's only available for 1P Business accounts. Would you mind providing some sample output from various invocations of `op list events`? I'm working on a stand-in utility to play back canned `op` responses for automated testing, and some representative output could be helpful

How impacted would you be if there is breaking API change in the near future? There are things I did early on that have become unwieldy that I'm hoping to rework. I'll try to keep API breakage to a minimum, and allow for a grace period of deprecation where possible.

**Comment by acabey-klaviyo** [comment]
On the matter of breaking changes, I am the sole developer for our little app here, and I am more than happy to make whatever API changes are necessary for our implementation to support your upstream improvements. I was actually planning on having a shot at adding in MFA support myself, which I see has been a lingering issue for a while.

I fully understand that you are still developing the project, and given that it is the only one out there to fill a much-needed niche in the 1Pass platform, I don't want you to feel held back from making big changes just because I might be impacted. Like I said, I think the most sustainable approach is to work with your upstream improvements as it will ultimately make for a better library.

On the matter of `op list events`, I've included my own documentation, which has effectively been reverse-engineered from our production data given the lack of proper documentation online. I will note, though, that our data most likely does not have complete coverage of all supported options / features, but at the very least should show enough to understand the common features and implement into the library.

## `op list events`

The command `op list events` is only available to OnePassword business accounts, and is relatively undocumented. This is
the OP CLI equivalent to the [activity log](https://support.1password.com/activity-log/). The CLI syntax is documented 
[here](https://support.1password.com/command-line/#list-activity-log-events) as 

`op list events [--eventid <event_ID>] [--older]`

The 100 most recent events will be listed.

### JSON output

The result of this command is a JSON-formatted list of event objects, e.g. (stripped details):
```json
[
  {
    "eid": #########,
    "time": "%Y-%m-%dT%H:%M:%SZ",
    "actorUuid": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "action": "patch",
    "objectType": "items",
    "objectUuid": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "auxInfo": "1,0,0,0,0"
  },
  {
    "eid": #########,
    "time": "%Y-%m-%dT%H:%M:%SZ",
    "actorUuid": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "action": "create",
    "objectType": "device",
    "objectUuid": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "auxUUID": "XXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  {
    "eid": #########,
    "time": "%Y-%m-%dT%H:%M:%SZ",
    "actorUuid": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "action": "join",
    "objectType": "gm",
    "objectUuid": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "auxInfo": "R",
    "auxUUID": "XXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  {
    "eid": #########,
    "time": "%Y-%m-%dT%H:%M:%SZ",
    "actorUuid": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "action": "activate",
    "objectType": "user",
    "objectUuid": "XXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  {
    "eid": #########,
    "time": "%Y-%m-%dT%H:%M:%SZ",
    "actorUuid": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "action": "grant",
    "objectType": "uva",
    "objectUuid": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "auxUUID": "XXXXXXXXXXXXXXXXXXXXXXXXXX"
  },
  {
    "eid": #########,
    "time": "%Y-%m-%dT%H:%M:%SZ",
    "actorUuid": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "action": "join",
    "objectType": "user",
    "objectUuid": "XXXXXXXXXXXXXXXXXXXXXXXXXX"
  }
]
```

### Actions

The minimal documentation on the support page claims that the following actions will be logged as events:

- Account Changes. Updating (changing team settings) and confirming.
- Billing. Adding and removing credit cards, updating subscriptions.
- Devices. Authorizing and removing devices.
- Email Changes. Beginning and completing email changes for team members.
- File Uploads. Creating (adding documents).
- Group Access. Adding, changing, and removing access to vaults.
- Groups. Creating and deleting, adding and removing team members, changing roles, and updating group details.
- Invitations. Inviting team members and guests.
- Linked Family Accounts. Generating codes, linking and unlinking family accounts.
- User Access. Adding, changing, and removing access to vaults.
- Users. Inviting, joining, and confirming.
- Vault Items. Updating (creating, editing, and deleting items, and emptying the Trash).
- Vaults. Creating and deleting.

From my own production data, I have found the following 'action's:

`create`
`delete`
`update`
`patch`
`grant`
`join`
`changemp`
`completr`
`beginr`

as well as the following 'objectType's:

`gva`
`vault`
`uva`
`user`
`items`
`device`
`file`
`gm`

I have reverse-engineered the following conventions based on production data:

| action   | Description               | objectUuid                                              | objectType | auxUUID                                               | aux Type | Notes                                                                                                                                                                                                                                                                                                         |
|----------|---------------------------|---------------------------------------------------------|------------|-------------------------------------------------------|----------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| create   | Create an object          | UUID of the (mfa) device created                        | device     | UUID of the user on which the MFA device applies      | user     |                                                                                                                                                                                                                                                                                                               |
|          |                           | UUID of the vault created                               | vault      | N/A                                                   | N/A      |                                                                                                                                                                                                                                                                                                               |
|          |                           | UUID of the file created                                | file       | N/A                                                   | N/A      |                                                                                                                                                                                                                                                                                                               |
| delete   | Delete an object          | UUID of the (mfa) device deleted                        | device     | UUID of the user from where the MFA device is deleted | user     |                                                                                                                                                                                                                                                                                                               |
| update   | Update an object          | UUID of the vault that has had its access updated       | gva        | UUID of the group whose access was updated            | gm       | Typically will immediately follow a "grant" action                                                                                                                                                                                                                                                            |
|          |                           | UUID of the vault that has had its access updated       | uva        | UUID of the user whose access was updated             | user     |                                                                                                                                                                                                                                                                                                               |
| grant    | Grant access to an object | UUID of the vault to where access has been granted      | uva        | UUID of the user who was granted access               | user     |                                                                                                                                                                                                                                                                                                               |
|          |                           | UUID of the vault to where access has been granted      | gva        | UUID of the group who was granted access              | gm       |                                                                                                                                                                                                                                                                                                               |
| patch    | "Update" items            | UUID of the vault wherein items were updated            | items      | N/A                                                   | N/A      | objectType is specified as "items", but is actually the UUID of a vault. I believe this actually represents updating a secret, but the API purposefully does not give the UUID of the secret "item" for security purposes, as even the admin should not have access to every item in every vault (by default) |
| join     | Add a user to a group     | UUID of the group where a user was added                | gm         | UUID of the user who was added to the group           | user     |                                                                                                                                                                                                                                                                                                               |
| changemp | Change master password    | UUID of the user whose master password was changed      | user       | N/A                                                   | N/A      |                                                                                                                                                                                                                                                                                                               |
| beginr   | Begin account recovery    | UUID of the user whose account is being recovered       | user       | N/A                                                   | N/A      |                                                                                                                                                                                                                                                                                                               |
| completr | Complete account recovery | UUID of the user whose account was completely recovered | user       | N/A                                                   | N/A      |                                                                                                                                                                                                                                                                                                               |

**Comment by zcutlip** [comment]
Wow, this is an amazing level of detail. It'll help when I get around to setting up tests.

I'll go ahead and merge this; it looks good.

Regarding MFA, please feel free to comment on issue #9, but I don't see a way forward. Since MFA is only required on initial sign-in, it may be reasonable to expect the user to manually do an initial sign-in first.

**Comment by zcutlip** [comment]
Merged PR #16. Need to write a few examples and then I'll cut a release and push to PyPI.

**Comment by zcutlip** [comment]
release 1.8.0 was pushed to PyPI which includes PR #16

**Pull request merged**
