### PR TITLE
Add file support

### PR DESCRIPTION
**Pull request by darkdreamingdan**
The library doesn't support file attachments right now.  Add a new `download` method to download items.

### CODE REVIEW

**Comment by darkdreamingdan** [comment]
@zcutlip , can you please review this? Would be great to get this into the latest version on pip

**Comment by zcutlip** [comment]
> @zcutlip , can you please review this? Would be great to get this into the latest version on pip

Hey thanks for your interest and for your patch!

I'm sorry I didn't jump on reviewing it right away, but unfortunately I do have a job, family, and other obligations. Plus we're in the middle of a global pandemic, so, you know, priorities.

I'm excited about your contribution and I'll get to it as soon as possible.

Cheers,
Zach

**Comment by darkdreamingdan** [comment]
No worries, wasn't sure if you were notified because it doesn't seem to let me set the 'Reviewers' on the PR.  Appreciate you taking a look :)

**Comment by zcutlip** [comment]
working on your PR now. It's really good! 

I'm trying to think of the best way to merge that doesn't make some other things I have planned more difficult.

I may merge it, but then make some api-breaking changes shortly thereafter. File attachment downloading would remain, but the API would likely change. I probably wouldn't push it to pypi until I get a few more things finalized. If I go that way, how does that sound?

**Comment by zcutlip** [comment]
Okay, I'm going to go ahead and merge, but stand by for further changes.

**Comment by darkdreamingdan** [comment]
Thanks so much for looking at this! Hope family and job are going okay during these times

**Comment by zcutlip** [comment]
Yeah you bet! Thanks for your PR; I think it's a useful feature. I hope to have the API pinned down soon, and I'll put it on pypi.

Doing fine here, just a bit stir crazy. Hope you're doing well also.

**Comment by zcutlip** [comment]
@darkdreamingdan Just wanted to let you know I made some of API changes as well as pushed a new release to pypi. You can now download using the `get_document()` method, which returns a (file name, document bytes) tuple. `download()` remains for the time being.

Thanks again for your contribution. Apologies for taking so long.

**Pull request merged**
